name: brain_game
description: A flutter brain game built using only pure flutter animations.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  just_audio: 
  flutter_svg: ^1.0.3
  soundpool: ^2.2.0
  flutter_native_splash:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  
flutter_native_splash: 
  color: "#CFE78C"
  image: "assets/images/splash_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Sansita
      fonts:
        - asset: assets/fonts/Sansita-Bold.ttf
         
    - family: RubikMonoOne
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf
          
